#!/bin/sh

qc_dir="/opt/genomics/IPHinvestigators/ccaggiano/previous_reference"
ilash_output=$qc_dir"/ilash"
mkdir -p $ilash_output
echo $ilash_output


### run ilash and calculate pileup 
for ((i=22; i>=1; i--))
do
    echo $i

    ## run ilash per chromosome 
    file=$qc_dir"/chr"$i"_converted"
    python generate_ilash_config_gillian_param.py $i $file".map" $file".ped" $ilash_output"/chr"$i".match"
    ./IBD_EXP1 "ilash_config_chr"$i

    ## calculate the amount of IBD at every position 
    python calculate_ibd_density.py $file".map" $ilash_output"/chr"$i".match" $ilash_output"/chr"$i"_depth.csv" $i


done

### combine the IBD statistics for all chromosomes 
for file in $ilash_output"/chr"*"_depth.csv";
do 
	cat $file >> $ilash_output"/all_depth.csv"; 
done


# identify the outliers to remove
python remove_outliers.py $ilash_output"/all_depth.csv" $ilash_output"/outliers.csv"

# merge overlapping windows in the bedfile generated by the remove_outlier.py script 
bedtools merge -i $ilash_output"/outliers.csv" > $ilash_output"/outliers_collapsed.csv"


### now per chromsome, remove the outliers and sum pairs together   
for ((i=22; i>=1; i--))
do
echo $i 

    combine_pairs.py $i $qc_dir"/chr"$i".match" $output_file ilash_output"/outliers_collapsed.csv"

done
